apiVersion: 1

datasources:
  - name: MSSQL
    type: mssql
    access: proxy
    url: mssql:1433
    user: sa
    secureJsonData:
      password: MsSqlPass123!
    jsonData:
      database: ecommerce_fraud_db
      encrypt: disable
    isDefault: true
    editable: true
